import { z } from 'zod';
import { getNextVoucherNo } from '../utils/voucher-number';

export function getPurchaseTools(supabase: any, companyId: string) {
  const mcpTool = (c: any) => c;
  return {
    lookupPurchases: mcpTool({
      description: 'Fetch recent purchase invoices from the database or search for a specific one',
      inputSchema: z.object({
        limit: z.number().optional().describe('Number of recent purchases to fetch. Default is 5.'),
        voucherNo: z.string().optional().describe('Specific voucher number to search for (e.g. P-1, P-42). If provided, searches for this specific purchase.'),
      }),
      execute: async ({ limit, voucherNo }: any) => {
        const fetchLimit = limit || 5;
        let query = supabase
          .from('transactions')
          .select(`
            id,
            voucher_no,
            date,
            total_amount,
            party:parties(name)
          `)
          .eq('voucher_type', 'PURCHASE')
          .eq('company_id', companyId)
          .order('date', { ascending: false });
          
        if (voucherNo) {
          query = query.eq('voucher_no', voucherNo);
        }
        
        const { data, error } = await query.limit(fetchLimit);
          
        if (error) throw new Error(error.message);
        
        return data.map((tx: any) => ({
          id: tx.id,
          voucherNo: tx.voucher_no,
          date: tx.date,
          totalAmount: tx.total_amount,
          supplierName: tx.party?.name || 'Unknown'
        }));
      },
    }),
    createPurchase: mcpTool({
      description: 'Creates a purchase invoice in the database. Returns the generated invoice number.',
      inputSchema: z.object({
        supplierId: z.string().describe('The ID of the supplier (party)'),
        date: z.string().describe('The invoice date in YYYY-MM-DD format'),
        items: z.array(z.object({
          itemId: z.string().describe('The ID of the item'),
          description: z.string().describe('The name/description of the item'),
          quantity: z.number().describe('Quantity purchased'),
          rate: z.number().describe('Price per unit'),
        })).describe('The line items on the purchase invoice'),
      }),
      execute: async ({ supplierId, date, items }: any) => {
        const totalAmount = items.reduce((sum: number, item: any) => sum + (item.quantity * item.rate), 0);
        const transactionId = crypto.randomUUID();

        const voucherNo = await getNextVoucherNo(supabase, 'PURCHASE', 'P', companyId);

        const { error: txError } = await supabase
          .from('transactions')
          .insert({
            id: transactionId,
            voucher_no: voucherNo,
            voucher_type: 'PURCHASE',
            date: date,
            party_id: supplierId,
            total_amount: totalAmount,
            notes: 'Generated by AI Assistant',
            company_id: companyId
          });

        if (txError) throw new Error(txError.message);

        const txItems = items.map((item: any) => ({
          id: crypto.randomUUID(),
          transaction_id: transactionId,
          item_id: item.itemId,
          description: item.description,
          quantity: item.quantity,
          rate: item.rate,
          amount: item.quantity * item.rate,
          company_id: companyId
        }));

        const { error: itemsError } = await supabase
          .from('transaction_items')
          .insert(txItems);

        if (itemsError) throw new Error(itemsError.message);

        return {
          success: true,
          voucherNo: voucherNo,
          totalAmount: totalAmount,
          message: "Purchase invoice saved successfully."
        };
      },
    }),
    getPurchaseSummary: mcpTool({
      description: 'Get total purchase amount for a specific date range',
      inputSchema: z.object({
        startDate: z.string().describe('Start date in YYYY-MM-DD format'),
        endDate: z.string().describe('End date in YYYY-MM-DD format'),
      }),
      execute: async ({ startDate, endDate }: any) => {
        const { data, error } = await supabase
          .from('transactions')
          .select('total_amount')
          .eq('voucher_type', 'PURCHASE')
          .eq('company_id', companyId)
          .gte('date', startDate)
          .lte('date', endDate);
          
        if (error) throw new Error(error.message);
        
        const totalPurchases = data.reduce((sum: number, tx: any) => sum + Number(tx.total_amount), 0);
        return {
          totalPurchases,
          count: data.length,
          period: `${startDate} to ${endDate}`
        };
      },
    }),
  };
}
