export async function insertTransactionWithJournalEntries(
  supabase: any,
  {
    transactionId,
    voucherNo,
    voucherType,
    date,
    partyId,
    totalAmount,
    notes,
    entries,
    companyId
  }: {
    transactionId: string;
    voucherNo: string;
    voucherType: string;
    date: string;
    partyId?: string;
    totalAmount: number;
    notes?: string;
    entries: { accountId: string; debit: number; credit: number }[];
    companyId: string;
  }
) {
  const { error: txError } = await supabase
    .from('transactions')
    .insert({
      id: transactionId,
      voucher_no: voucherNo,
      voucher_type: voucherType,
      date: date,
      party_id: partyId,
      total_amount: totalAmount,
      notes: notes || 'Generated by AI Assistant',
      company_id: companyId
    });

  if (txError) throw new Error(txError.message);

  const journalEntries = entries.map((entry) => ({
    id: crypto.randomUUID(),
    transaction_id: transactionId,
    account_id: entry.accountId,
    debit: entry.debit,
    credit: entry.credit,
    company_id: companyId
  }));

  const { error: jeError } = await supabase.from('journal_entries').insert(journalEntries);
  if (jeError) throw new Error(jeError.message);
}

