import { google } from '@ai-sdk/google';
import { streamText, tool, convertToModelMessages, stepCountIs } from 'ai';
import { z } from 'zod';
import { supabase } from '@/lib/supabase';

// Allow streaming responses up to 30 seconds
export const maxDuration = 30;

export async function POST(req: Request) {
  const { messages } = await req.json();

  // In AI SDK v6, messages use `parts` format (UIMessage[]).
  // convertToModelMessages handles the UIMessage -> ModelMessage conversion.
  const modelMessages = await convertToModelMessages(messages);

  const result = streamText({
    model: google('gemini-2.5-flash'),
    messages: modelMessages,
    stopWhen: stepCountIs(5),
    system: `You are QuickInvoice AI, an expert, incredibly fast AI accountant assistant.
    Your job is to help the business owner manage their accounting via a chat interface.
    
    You have direct access to their live cloud database via tools.
    If they ask to create an invoice, you should ALWAYS:
    1. Look up the customer name to get their ID. You MUST pass the nameQuery argument.
    2. Look up the item names to get their IDs. You MUST pass the nameQuery argument.
    3. Call the createInvoice tool with the correct IDs, quantities, and rates.
    
    Be concise, helpful, and professional.`,
    tools: {
      lookupCustomers: tool({
        description: 'Search for customers by name',
        inputSchema: z.object({
          nameQuery: z.string().describe('The name or partial name of the customer to search for'),
        }),
        execute: async ({ nameQuery }) => {
          const query = nameQuery || '';
          const { data, error } = await supabase
            .from('parties')
            .select('id, name, phone, address')
            .ilike('name', `%${query}%`)
            .limit(5);
          
          if (error) throw new Error(error.message);
          return data;
        },
      }),
      lookupItems: tool({
        description: 'Search for inventory items/products by name',
        inputSchema: z.object({
          nameQuery: z.string().describe('The name or partial name of the item to search for'),
        }),
        execute: async ({ nameQuery }) => {
          const query = nameQuery || '';
          const { data, error } = await supabase
            .from('items')
            .select('id, name, default_rate, unit')
            .ilike('name', `%${query}%`)
            .limit(5);
          
          if (error) throw new Error(error.message);
          return data;
        },
      }),
      createInvoice: tool({
        description: 'Creates a sales invoice in the database. Returns the generated invoice number.',
        inputSchema: z.object({
          customerId: z.string().describe('The ID of the customer'),
          date: z.string().describe('The invoice date in YYYY-MM-DD format'),
          items: z.array(z.object({
            itemId: z.string().describe('The ID of the item'),
            description: z.string().describe('The name/description of the item'),
            quantity: z.number().describe('Quantity sold'),
            rate: z.number().describe('Price per unit'),
          })).describe('The line items on the invoice'),
        }),
        execute: async ({ customerId, date, items }) => {
          const totalAmount = items.reduce((sum, item) => sum + (item.quantity * item.rate), 0);
          
          const transactionId = crypto.randomUUID();

          // Generate next sequential voucher number (same logic as desktop app)
          const prefix = 'S'; // SALES prefix
          const { data: existingVouchers } = await supabase
            .from('transactions')
            .select('voucher_no')
            .eq('voucher_type', 'SALES');

          const suffixRegex = /(?:^|[^0-9])(\d+)$/;
          const maxNo = (existingVouchers ?? []).reduce((max, row) => {
            const match = row.voucher_no?.match(suffixRegex);
            if (!match) return max;
            const n = parseInt(match[1], 10);
            return n > max ? n : max;
          }, 0);

          const voucherNo = `${prefix}-${maxNo + 1}`;

          const { error: txError } = await supabase
            .from('transactions')
            .insert({
              id: transactionId,
              voucher_no: voucherNo,
              voucher_type: 'SALES',
              date: date,
              party_id: customerId,
              total_amount: totalAmount,
              notes: 'Generated by AI Assistant'
            });

          if (txError) throw new Error(txError.message);

          const txItems = items.map(item => ({
            id: crypto.randomUUID(),
            transaction_id: transactionId,
            item_id: item.itemId,
            description: item.description,
            quantity: item.quantity,
            rate: item.rate,
            amount: item.quantity * item.rate
          }));

          const { error: itemsError } = await supabase
            .from('transaction_items')
            .insert(txItems);

          if (itemsError) throw new Error(itemsError.message);

          return {
            success: true,
            voucherNo: voucherNo,
            totalAmount: totalAmount,
            message: "Invoice saved successfully. The desktop app will automatically process the ledgers shortly."
          };
        },
      }),
    },
  });

  return result.toUIMessageStreamResponse();
}
